---
- name: install several packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - chrony
    - htop
    - telnet
    - nmap
    - screen
    - tcpdump
    - iptraf 
    - sudo
    - bridge-utils

- name: set timezone
  timezone: name="{{ timezone }}"

- name: generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - en_US.UTF-8
    - ru_RU.UTF-8

- name: configure chrony
  template:
    src: "templates/chrony.j2"
    dest: "/etc/chrony/chrony.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart chrony

- name: start and enable chrony
  service: name=chrony state=started enabled=yes

- name: configure journald
  template: 
    src: templates/journald.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0644
  notify: restart journald

...
