---
- name: restart networking
  service: name=networking state=restarted
  ignore_errors: yes

- name: restart chrony
  service: name=chrony state=restarted

- name: restart journald
  service: name=systemd-journald state=restarted 

- name: reboot
  reboot:
